config/routes.rb
Rails.application.routes.draw do
  resources :cats
  get 'users/show'
  root 'home#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    resources :users, :only => [:show, :edit, :update]

  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_many :user, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]

  # GET /cats or /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1 or /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats or /cats.json
  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: "Cat was successfully created." }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1 or /cats/1.json
  def update
    @cat.user_id = current_user.id
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: "Cat was successfully updated." }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1 or /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: "Cat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_params
      params.require(:cat).permit(:user_id, :name, :prefectures, :introduction, :image)
    end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<%= form_with(model: cat) do |form| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
        <% cat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="profile">
    <div class="field">
      <%= form.label :name %> <br>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :prefectures %> <br>
      <%= form.text_field :prefectures %>
    </div>

    <div class="field">
      <%= form.label :introduction %> <br>
      <%= form.text_area :introduction %>
    </div>

    <div class="field">
      <%= form.label :image %> <br>
      <%= form.file_field :image %>
    </div> <br>

    <div class="actions">
      <%= form.submit  class:"btn btn-warning" %>
    </div>
  </div>
<% end %>

app/views/cats/edit.html.erb
<div class="content">
  <div class="contentbox show_box">
    <h2>保護ねこ情報変更</h2>
    <%= render 'form', cat: @cat %>
    <div class="btnitems">
      <%= link_to '詳細', @cat %>
    </div>
  </div>
</div>

app/views/cats/index.html.erb
<div class="content">
  <div class="contentbox show_box">
    <p id="notice"><%= notice %></p>
    <h2><%= current_user.name %>さんの保護ねこ一覧</h2>
    <div class="profile">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ねこ名</th>
            <th scope="col">紹介文</th>
            <th scope="col">画像</th>
            <th colspan="3" scope="col"></th>
          </tr>
        </thead>

        <tbody>
          <% @cats.each do |cat| %>
            <tr>
              <%= link_to cat do %>
                <td><%= link_to cat.name, cat %></td>
                <td><%= cat.introduction %></td>
                <td>
                  <% if cat.image? %>
                    <%= image_tag cat.image.url, size: '100x100', class:"myimage" %>
                  <% end %>
                </td>
              <% end %>
              <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
              <td><%= link_to 'Destroy', cats_path(cat), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/cats/new.html.erb
<div class="content">
  <div class="contentbox show_box">
    <h2>保護ねこを登録</h2>
    <%= render 'form', cat: @cat %>
    <div class="btnitems">
    </div>
  </div>
</div>

app/views/cats/show.html.erb
<div class="content">
  <div class="contentbox show_box">

    <p id="notice"><%= notice %></p>

    <h2>
      ねこの名前:<%= @cat.name %>
    </h2>

    <p>
      <% if @cat.image? %>
        <%= image_tag @cat.image.url, size: '200x200', class:"myimage" %>
      <% end %>
    </p>
    
    <div class="profile">
    <p>
      <strong>保護者名:</strong>
      <%= @cat.user.name %> さん
    </p>

    <p>
      <strong>都道府県:</strong>
      <%= @cat.prefectures %>
    </p>

    <p>
      <strong>紹介文:</strong>
      <%= @cat.introduction %>
    </p>
    </div>


    <div class="btnitems">
      <%= link_to '編集', edit_cat_path(@cat) %> |
      <%= link_to '戻る', cats_path %>
    </div>
  </div>
</div>