config/routes.rb
Rails.application.routes.draw do
  resources :cats
  get 'users/show'
  root 'home#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    resources :users, :only => [:show, :edit, :update]

  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="footer">
        <p>©︎kumakuma</p>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid ">
      
      <a class="navbar-brand" href="/"><%= image_tag 'catapp.png', :height => '60' %></a>

      <div class="pull-right">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'マイページ', user_path(current_user), method: :delete, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to '保護ねこ登録', new_cat_path(current_user), method: :delete, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to '登録ねこ一覧', cats_path(current_user), method: :delete, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to '新規登録', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <form class="d-flex", style="padding: 15px">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CAT-app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>